import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './components/sidebar'
import 'rsuite/dist/rsuite.min.css';
import { CustomProvider } from 'rsuite';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <CustomProvider theme='dark'>{children}</CustomProvider>
      </body>
    </html>
  )
}
